(define (square n) (* n n))
(define (fast-expt b n)
  (cond ((= n 0) 1)
    ((even? n) (square (fast-expt b (/ n 2))))
    (else (* b (fast-expt b (- n 1))))))

(define (fast-expo b n a)
  (cond ((= n 0) a)
    ((even? n) (fast-expo (square b) (/ n 2) a))
    (else (fast-expo b (- n 1) (* a b)))))